### ISSUE TITLE
morning session P2P code review:

### ISSUE THREAD

**Issue by Sammy3000** [Donmark2k/leaderboard#7]
### Highlights:
- Your code has been implemented asynchronously well using async and await.
- Your code is well organized using modules and it is easy to read and understand.
- Nice job implementing sorting in your list.
- Your UI is well styled and interactive.
- (OPTIONAL) Kindly include feature in your featured section or just delete it from the template if not required.

**Comment by Donmark2k** [comment]
Rectify the issue
